### ISSUE TITLE
[US13 e US14] Criar endpoint de exercícios

### ISSUE THREAD

**Issue by SwampTG** [UnBArqDsw2022-1/2022_1_G5_SerFit#96]
### Summary

Disponibilizar endpoint tipo GET para exercícios e categorias.

## Critérios de aceitação:

Endpoints com a listagem de atividades para serem inseridas em um plano
- [x] Lista de exercícios
- [x] Exercício por ID
- [x] Lista de categorias
- [x] Categoria por ID
- [ ] O endpoint deverá ser documentado em um arquivo Swagger
- [ ] O código deverá seguir a modelagem proposta
- [ ] Se necessário, os arquivos de documentação devem ser alterados

### Motivation

Facilitar interação entre os usuários

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luis-gustavo** [comment]
Fechado por [PR](https://github.com/UnBArqDsw2022-1/2022.1_G5_SerFit_Backend/pull/6)
